### ISSUE TITLE
Major Client Crash

### ISSUE THREAD

**Issue by fcpwiz** [M3gaFr3ak/ExtraCells2#165]
Here: https://gist.github.com/fcpwiz/ebe9da0d4e3de3f72135

**Comment by lehjr** [comment]
You can't mix Applied Energistics RV1 and Extra Cells RV2. Furthermore, there's not much reason to use  AE2-RV1 unless you are using a mod that relies on it. The "stable" label in AE2-RV1-Stable doesn't mean that it is bug/crash free, it just means that it is unchanging (will never change because it isn't being updated).

**Comment by fcpwiz** [comment]
@lehjr Oh. So should I get AE Rv 2, or get ExtraCells Rv 1 and keep AE Rv 1?

**Comment by lehjr** [comment]
I would get AE RV2. It has several bug fixes, performance enhancements, and the channels now show up in WAILA again. Just note that if you plan to use Thaumic Energistics, it isn't compatible with AE2-RV2-beta 8 yet.
